<?php

/**
 * ConsolidationResponse
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Walmart
 * @author   Jesse Evers
 * @link     https://highsidelabs.co
 * @email    jesse@highsidelabs.co
 */

/**
 * International Shipping
 *
 * This class is auto-generated by the OpenAPI generator v6.6.0 (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

namespace Walmart\Models\MP\CA\InternationalShipping;

use Walmart\Models\BaseModel;

/**
 * ConsolidationResponse Class Doc Comment
 *
 * @category Class

 * @description data

 * @package  Walmart
 * @author   Jesse Evers
 * @link     https://highsidelabs.co
 * @email    jesse@highsidelabs.co
 */
class ConsolidationResponse extends BaseModel
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'ConsolidationResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static array $openAPITypes = [
        'consolidationId' => 'int',
        'shipmentIds' => 'string[]',
        'domesticTrackingNo' => 'string',
        'domesticCarrierId' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'consolidationId' => 'int64',
        'shipmentIds' => null,
        'domesticTrackingNo' => null,
        'domesticCarrierId' => 'int32'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'consolidationId' => false,
        'shipmentIds' => false,
        'domesticTrackingNo' => false,
        'domesticCarrierId' => false
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static array $attributeMap = [
        'consolidationId' => 'consolidationId',
        'shipmentIds' => 'shipmentIds',
        'domesticTrackingNo' => 'domesticTrackingNo',
        'domesticCarrierId' => 'domesticCarrierId'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static array $setters = [
        'consolidationId' => 'setConsolidationId',
        'shipmentIds' => 'setShipmentIds',
        'domesticTrackingNo' => 'setDomesticTrackingNo',
        'domesticCarrierId' => 'setDomesticCarrierId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static array $getters = [
        'consolidationId' => 'getConsolidationId',
        'shipmentIds' => 'getShipmentIds',
        'domesticTrackingNo' => 'getDomesticTrackingNo',
        'domesticCarrierId' => 'getDomesticCarrierId'
    ];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('consolidationId', $data ?? [], null);
        $this->setIfExists('shipmentIds', $data ?? [], null);
        $this->setIfExists('domesticTrackingNo', $data ?? [], null);
        $this->setIfExists('domesticCarrierId', $data ?? [], null);
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];


        return $invalidProperties;
    }

    /**
     * Gets consolidationId
     *
     * @return int|null
    
     */
    public function getConsolidationId()
    {
        return $this->container['consolidationId'];
    }

    /**
     * Sets consolidationId
     *
     * @param int|null $consolidationId ConsolidationId.
     *
     * @return self
    
     */
    public function setConsolidationId($consolidationId)
    {
        if (is_null($consolidationId)) {
            throw new \InvalidArgumentException('non-nullable consolidationId cannot be null');
        }

        $this->container['consolidationId'] = $consolidationId;
        return $this;
    }

    /**
     * Gets shipmentIds
     *
     * @return string[]|null
    
     */
    public function getShipmentIds()
    {
        return $this->container['shipmentIds'];
    }

    /**
     * Sets shipmentIds
     *
     * @param string[]|null $shipmentIds ShipmentIds.
     *
     * @return self
    
     */
    public function setShipmentIds($shipmentIds)
    {
        if (is_null($shipmentIds)) {
            throw new \InvalidArgumentException('non-nullable shipmentIds cannot be null');
        }

        $this->container['shipmentIds'] = $shipmentIds;
        return $this;
    }

    /**
     * Gets domesticTrackingNo
     *
     * @return string|null
    
     */
    public function getDomesticTrackingNo()
    {
        return $this->container['domesticTrackingNo'];
    }

    /**
     * Sets domesticTrackingNo
     *
     * @param string|null $domesticTrackingNo Domestic Tracking No.
     *
     * @return self
    
     */
    public function setDomesticTrackingNo($domesticTrackingNo)
    {
        if (is_null($domesticTrackingNo)) {
            throw new \InvalidArgumentException('non-nullable domesticTrackingNo cannot be null');
        }

        $this->container['domesticTrackingNo'] = $domesticTrackingNo;
        return $this;
    }

    /**
     * Gets domesticCarrierId
     *
     * @return int|null
    
     */
    public function getDomesticCarrierId()
    {
        return $this->container['domesticCarrierId'];
    }

    /**
     * Sets domesticCarrierId
     *
     * @param int|null $domesticCarrierId Domestic CarrierId.
     *
     * @return self
    
     */
    public function setDomesticCarrierId($domesticCarrierId)
    {
        if (is_null($domesticCarrierId)) {
            throw new \InvalidArgumentException('non-nullable domesticCarrierId cannot be null');
        }

        $this->container['domesticCarrierId'] = $domesticCarrierId;
        return $this;
    }
}


