<?php

/**
 * RatingReviews
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Walmart
 * @author   Jesse Evers
 * @link     https://highsidelabs.co
 * @email    jesse@highsidelabs.co
 */

/**
 * Insights Management
 *
 * This class is auto-generated by the OpenAPI generator v6.6.0 (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

namespace Walmart\Models\MP\US\Insights;

use Walmart\Models\BaseModel;

/**
 * RatingReviews Class Doc Comment
 *
 * @category Class

 * @package  Walmart
 * @author   Jesse Evers
 * @link     https://highsidelabs.co
 * @email    jesse@highsidelabs.co
 */
class RatingReviews extends BaseModel
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'RatingReviews';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static array $openAPITypes = [
        'maxRating' => 'string',
        'ratingCount' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'maxRating' => null,
        'ratingCount' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'maxRating' => false,
        'ratingCount' => false
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static array $attributeMap = [
        'maxRating' => 'maxRating',
        'ratingCount' => 'ratingCount'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static array $setters = [
        'maxRating' => 'setMaxRating',
        'ratingCount' => 'setRatingCount'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static array $getters = [
        'maxRating' => 'getMaxRating',
        'ratingCount' => 'getRatingCount'
    ];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('maxRating', $data ?? [], null);
        $this->setIfExists('ratingCount', $data ?? [], null);
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];


        return $invalidProperties;
    }

    /**
     * Gets maxRating
     *
     * @return string|null
    
     */
    public function getMaxRating()
    {
        return $this->container['maxRating'];
    }

    /**
     * Sets maxRating
     *
     * @param string|null $maxRating maxRating
     *
     * @return self
    
     */
    public function setMaxRating($maxRating)
    {
        if (is_null($maxRating)) {
            throw new \InvalidArgumentException('non-nullable maxRating cannot be null');
        }

        $this->container['maxRating'] = $maxRating;
        return $this;
    }

    /**
     * Gets ratingCount
     *
     * @return string|null
    
     */
    public function getRatingCount()
    {
        return $this->container['ratingCount'];
    }

    /**
     * Sets ratingCount
     *
     * @param string|null $ratingCount ratingCount
     *
     * @return self
    
     */
    public function setRatingCount($ratingCount)
    {
        if (is_null($ratingCount)) {
            throw new \InvalidArgumentException('non-nullable ratingCount cannot be null');
        }

        $this->container['ratingCount'] = $ratingCount;
        return $this;
    }
}
